apiVersion: v1
kind: Service
metadata:
  name: order-processing
spec:
  selector:
    io.kompose.service: order-processing
  ports:
    - name: "http"
      port: 80
      targetPort: 5000
      nodePort: 31002 # Choose a suitable port number for the nodePort field
  type: NodePort
