apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: product-management
  name: product-management
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: product-management
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/microservices_network: "true"
        io.kompose.service: product-management
    spec:
      containers:
        - image: pes2ug21cs134chandana/product_manage:latest
          name: product-management-container
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
