apiVersion: v1
kind: Service
metadata:
  name: product-management
spec:
  selector:
    io.kompose.service: product-management
  ports:
    - name: "http"
      port: 80
      targetPort: 5000
      nodePort: 31003 # Choose a suitable port number for the nodePort field
  type: NodePort
