apiVersion: v1
kind: Service
metadata:
  name: user-auth
spec:
  selector:
    io.kompose.service: user-auth
  ports:
    - name: "http"
      port: 80
      targetPort: 5000
      nodePort: 31001 # Choose a suitable port number for the nodePort field
  type: NodePort
